title: Photography
cover: witchesgrove.jpg
sections:
 - type: pictures-group
   images:
    -
     - name: witchesgrove.jpg
    -
     - name: columns.jpg
    -
     - name: molerabeach.png
    -
     - name: roadsidetemple.jpg
    -
     - name: jauneetbleu.jpg
     - name: burningbarrel.jpg
     - name: shimmer.jpg
    -
     - name: feuillesjaunesdenuit.jpg
     - name: feuillesvertesdenuit.jpg
     - name: arbredenuit.jpg
    -
     - name: mixing.jpg
     - name: power.jpg
     - name: dehiscence.jpg
    -
     - name: rose.jpg
     - name: naps.jpg
    -
     - name: risperidonenoiseless1.jpg
     - name: risperidonenoiseless2.jpg
     - name: risperidonenoiseless3.jpg
    -
     - name: risperidonerustle.jpg
    -
     - name: risperidonerustle1.jpg
     - name: risperidonerustle2.jpg
     - name: risperidonerustle3.jpg
    -
     - name: frigid.jpg
     - name: 17th.jpg
